name: flutter_firebase_app
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.10
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  get: ^4.6.6
  image_picker: ^1.0.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
assets:
  - assets/logos/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/logo.jpg
  #  android_12:
  #    image: assets/png_images/android12_logo.png
  #    icon_background_color: "#111111"

  android: true
  ios: true
  web: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
